import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navbar";
import { LoadingProvider } from "@/context/LoadingContext";
import NavigationHandler from "@/components/NavigationHandler";
import CustomCursor from "@/hooks/useCustomCursor";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import SmoothScroll from "@/hooks/useSmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black antialiased`}
      >
         <SmoothScroll />
         <CustomCursor />
        <LoadingProvider>
           <Suspense fallback={null /* or a tiny loader */}>
          <NavigationHandler>
         <Header />
        {children}
        <Footer/>
        </NavigationHandler>
        </Suspense>
         </LoadingProvider>
      </body>
    </html>
  );
}
